name: ska_connect
description: Support library for making request with the Connect (connect.build) protocol. Intended for use with generated code.
issue_tracker: https://github.com/skadero/connect_dart/issues
repository: https://github.com/skadero/connect_dart

version: "1.0.1"

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5
  protobuf: "^2.0.0"

dev_dependencies:
  test: ^1.21.0
