name: connect_dart
description: Utility library for Connect protocol

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5
  protobuf: "^2.0.0"

dev_dependencies:
  test: ^1.21.0
